name: Avatar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          pip install --upgrade pip
          pip install build
          pip install .
      - name: Build
        run: python -m build
  lint:
    name: Lint for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: pip install .[dev]
      - run: mypy
      - run: pyright
  format:
    name: Check Python formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install
        run: |
          pip install --upgrade pip
          pip install .[dev]
      - run: black --check avatar/
      - run: isort --check avatar
  test:
    name: Test Bumble vs Bumble(s) [${{ matrix.shard }}/24]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [
           1,  2,  3,  4,  5,  6,  7,  8,
           9, 10, 11, 12, 13, 14, 15, 16,
          17, 18, 19, 20, 21, 22, 23, 24,
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install
        run: |
          pip install --upgrade pip
          pip install rootcanal==1.3.0
          pip install .
          mkdir -p out
      - name: Rootcanal
        run: nohup python -m rootcanal > out/rootcanal.log &
      - name: Test
        run: |
          avatar --list | grep -Ev '^=' > test-names.txt
          timeout 5m avatar --test-beds bumble.bumbles --tests $(split test-names.txt -n l/${{ matrix.shard }}/24)
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: artifacts_${{ matrix.shard }}
          path: out/
